### PR TITLE
Add extended euclidean algorithm

### PR DESCRIPTION
**Pull request by Multramate**
Added an extended Euclidean algorithm function `gcdExt` in `Data/Poly/Internal/Sparse/Fractional.hs` for `Num` and `Semiring` polynomials to continue addressing #22, as well as several simple tests and benchmarks. This mirrors the implementation in `Data/Poly/Internal/Dense/Fractional.hs` and as such is also unoptimised. The tests and benchmarks have shown that this is even slower than the dense `gcdExt`, but this makes sense.

As you said, GCD operations shouldn't be done with sparse polynomials, so wouldn't this be unnecessary as well? There could also be a convenient conversion function that switches between the dense and sparse flavours.

### CODE REVIEW

**Comment by Bodigrim** [comment]
Could you please rebase your branch?

> As you said, GCD operations shouldn't be done with sparse polynomials, so wouldn't this be unnecessary as well? 

As we discussed in https://github.com/Bodigrim/poly/issues/22#issuecomment-523219832, it is unwise to use `gcd` with a sparse representation (because in general a quotient of sparse polynomials is dense). This is why the performance of sparse `gcd` / `gcdExt` does not matter. But I am still keen to provide a consistent API for both dense and sparse flavors. 

The reason is that I prefer to use sparse polynomials for quick experiments in REPL: their `Show` instance is more readable, because there are no zero coefficients listed. Compare

```
> Data.Euclidean.gcd (Data.Poly.Sparse.X ^ 99 - 1) (Data.Poly.Sparse.X ^ 66 - 1) :: Data.Poly.Sparse.UPoly Int
1 * X^33 + (-1)
```

vs.

```
> Data.Euclidean.gcd (Data.Poly.X ^ 99 - 1) (Data.Poly.X ^ 66 - 1) :: Data.Poly.UPoly Int
1 * X^33 + 0 * X^32 + 0 * X^31 + 0 * X^30 + 0 * X^29 + 0 * X^28 + 0 * X^27 + 0 * X^26 + 0 * X^25 + 0 * X^24 + 0 * X^23 + 0 * X^22 + 0 * X^21 + 0 * X^20 + 0 * X^19 + 0 * X^18 + 0 * X^17 + 0 * X^16 + 0 * X^15 + 0 * X^14 + 0 * X^13 + 0 * X^12 + 0 * X^11 + 0 * X^10 + 0 * X^9 + 0 * X^8 + 0 * X^7 + 0 * X^6 + 0 * X^5 + 0 * X^4 + 0 * X^3 + 0 * X^2 + 0 * X + (-1)
```

**Comment by Multramate** [comment]
Right, my bad.

File: src/Data/Poly/Internal/Sparse/Fractional.hs [hunk 1]
```diff
@@ -58,6 +59,50 @@ quotientRemainder ts ys = case leading ys of
             zs = Poly $ G.singleton (xp - yp, xc / yc)
             xs' = xs - zs * ys
 
+-- | Execute the extended Euclidean algorithm.
+-- For polynomials 'a' and 'b', compute their unique greatest common divisor 'g'
```
Comment (Bodigrim) [inline src/Data/Poly/Internal/Sparse/Fractional.hs]: Single quotes in Haddock mean that the enclosed string is an identifier in scope. I suppose you meant to achieve monospace typesetting. In this case use `@a@`, `@b@`, etc.

File: test/Dense.hs [hunk 2]
```diff
@@ -281,5 +281,4 @@ gcdExtTests = localOption (QuickCheckMaxSize 12) $ testGroup "gcdExt"
 sameUpToUnits :: (Eq a, GcdDomain a) => a -> a -> Bool
 sameUpToUnits x y = x == y ||
   isJust (x `divide` y) && isJust (y `divide` x)
-
```
Comment (Bodigrim) [inline test/Dense.hs]: I believe this is a merge artifact?

Comment (Multramate) [reply test/Dense.hs]: Yeah - I tried to make the spacing consistent with the rest of the module.

**Comment by Multramate** [comment]
I honestly have no clue why the Travis CI build fails.

**Comment by Bodigrim** [comment]
At the moment `quickcheck-classes` fails to build against `semirings-0.5`. 
https://github.com/andrewthad/quickcheck-classes/pull/112

But earlier I spotted a failure in build against `semirings-0.3.1.2` (https://travis-ci.org/Bodigrim/poly/jobs/580974594):
```
src/Data/Poly/Sparse.hs:34:46: error:
    Module
    ‘Data.Poly.Internal.Sparse.Fractional’
    does not export
    ‘gcdExt’
   |
34 | import Data.Poly.Internal.Sparse.Fractional (gcdExt)
   |           
```

Probably you can fix it similar to dense polynomials in `Data.Poly`.

**Comment by Multramate** [comment]
Addressed #30.

**Comment by Bodigrim** [comment]
The issue with `quickcheck-classes` has been fixed, but builds still fail. Could you possibly investigate? I suspect that it is mostly caused by dd73f6a29b8ad240d5ca766ceceeafd84c6f0244.

It may be reasonable to rebase/upmerge/cherry-pick a214db60be9aa36097d7bf30e0e8df8cfa0eaa02 - this commit improves wall time of Travis builds.

**Comment by Multramate** [comment]
Above is a temporary solution, since `Fractional` and `Field` are not really superclasses of each other.

**Comment by Multramate** [comment]
Whoops

**Comment by Bodigrim** [comment]
Thanks, merged!
